version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
    - "5672:5672"
    - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: myUser
      RABBITMQ_DEFAULT_PASS: myPassword

  server:
    image: jpleorx/worker-proxy-server
    restart: always
    ports:
      - "8888:8888"
    environment:
      WORKER_PROXY_RABBITMQ_HOST: rabbitmq
      WORKER_PROXY_RABBITMQ_PORT: 5672
      WORKER_PROXY_RABBITMQ_USERNAME: myUser
      WORKER_PROXY_RABBITMQ_PASSWORD: myPassword

  clientA:
    image: jpleorx/worker-proxy-client
    restart: always
    ports:
      - "7771:7777"
    environment:
      WORKER_PROXY_RABBITMQ_HOST: rabbitmq
      WORKER_PROXY_RABBITMQ_PORT: 5672
      WORKER_PROXY_RABBITMQ_USERNAME: myUser
      WORKER_PROXY_RABBITMQ_PASSWORD: myPassword
      WORKER_PROXY_CLIENT_PROXIED_BASE_URL: http://workerA:7000/

  clientB:
    image: jpleorx/worker-proxy-client
    restart: always
    ports:
      - "7772:7777"
    environment:
      WORKER_PROXY_RABBITMQ_HOST: rabbitmq
      WORKER_PROXY_RABBITMQ_PORT: 5672
      WORKER_PROXY_RABBITMQ_USERNAME: myUser
      WORKER_PROXY_RABBITMQ_PASSWORD: myPassword
      WORKER_PROXY_CLIENT_PROXIED_BASE_URL: http://workerB:7000/

  workerA:
    image: worker-proxy-sample-service
    restart: always
    ports:
      - "7001:7000"

  workerB:
    image: worker-proxy-sample-service
    restart: always
    ports:
      - "7002:7000"
